apiVersion: apollographql.com/v1alpha2
kind: Subgraph
metadata:
  name: shipping
  namespace: shipping
  labels:
    app: shipping
    apollo.io/subgraph: "true"
spec:
  endpoint: http://graphql.shipping.svc.cluster.local:4001
  schema:
    ociImage:
      reference: ghcr.io/${GITHUB_ORG}/reference-architecture/shipping:main
      path: /app/schema.graphql
