apiVersion: apollographql.com/v1alpha2
kind: Supergraph
metadata:
  name: reference-architecture-prod
  namespace: apollo
spec:
  replicas: 3
  podTemplate:
    routerVersion: 2.3.0
    env:
      - name: APOLLO_ROUTER_LOG
        value: "warn"
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
  schema:
    resource:
      name: reference-architecture-prod
      namespace: apollo

