apiVersion: apollographql.com/v1alpha2
kind: Supergraph
metadata:
  name: reference-architecture-prod
  namespace: apollo
spec:
  replicas: 3
  serviceName: router
  podTemplate:
    routerVersion: 1.37.0
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
  schema:
    resource:
      name: reference-architecture-prod
      namespace: apollo

