apiVersion: apollographql.com/v1alpha2
kind: Subgraph
metadata:
  name: users
  namespace: users
  labels:
    app: users
    apollo.io/subgraph: "true"
spec:
  endpoint: http://graphql.users.svc.cluster.local:4001
  schema:
    ociImage:
      reference: ghcr.io/${GITHUB_ORG}/reference-architecture/users:main
      path: /app/schema.graphql
