apiVersion: apollographql.com/v1alpha2
kind: Subgraph
metadata:
  name: reviews
  namespace: reviews
  labels:
    app: reviews
    apollo.io/subgraph: "true"
spec:
  endpoint: http://graphql.reviews.svc.cluster.local:4001
  schema:
    ociImage:
      reference: ghcr.io/${GITHUB_ORG}/reference-architecture/reviews:main
      path: /app/schema.graphql
