apiVersion: apollographql.com/v1alpha2
kind: Subgraph
metadata:
  name: orders
  namespace: orders
  labels:
    app: orders
    apollo.io/subgraph: "true"
spec:
  endpoint: http://graphql.orders.svc.cluster.local:4001
  schema:
    ociImage:
      reference: ghcr.io/${GITHUB_ORG}/reference-architecture/orders:main
      path: /app/schema.graphql
